import { Hono } from 'hono'
import type { FC } from 'hono/jsx'

const Page: FC = () => (
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Hono + Bun + Inline Source</title>
      <link inline rel="stylesheet" href="/src/style.css" />
    </head>
    <body class="bg-amber-50 text-slate-900">
      <div class="min-h-screen px-6 py-12">
        <div class="mx-auto max-w-4xl">
          <header class="animate-[fadeIn_0.6s_ease-out] flex flex-col gap-6 md:flex-row md:items-end md:justify-between">
            <div class="max-w-2xl">
              <p class="text-[0.62rem] uppercase tracking-[0.45em] text-teal-700">Inline demo</p>
              <h1 class="mt-3 text-4xl font-semibold tracking-tight text-slate-900 md:text-5xl">
                Bun plugin playground
              </h1>
              <p class="mt-4 text-sm text-slate-600">
                Test Bun plugins with unplugin-inline-source and bun-plugin-tailwind. The CSS and
                client JS are inlined during the build step.
              </p>
            </div>
            <div class="flex flex-wrap gap-2 text-xs">
              <span class="rounded-full border border-amber-300 bg-amber-100 px-3 py-1 text-amber-700">
                Tailwind v4
              </span>
              <span class="rounded-full border border-slate-200 bg-white/70 px-3 py-1 text-slate-600">
                Bun plugin
              </span>
            </div>
          </header>

          <main class="mt-10 grid gap-6 md:grid-cols-[1.1fr_0.9fr]">
            <section class="animate-[fadeUp_0.7s_ease-out] rounded-3xl border border-amber-200/70 bg-white/90 p-7 shadow-[0_24px_60px_-40px_rgba(15,23,42,0.25)]">
              <h2 class="text-xl font-semibold text-slate-900">Inline sources</h2>
              <ul class="mt-4 space-y-3 text-sm text-slate-600">
                <li class="flex items-start gap-2">
                  <span class="mt-1 h-2 w-2 rounded-full bg-amber-500"></span>
                  <span><strong class="text-slate-900">/src/style.css</strong> is inlined via &lt;link inline&gt;</span>
                </li>
                <li class="flex items-start gap-2">
                  <span class="mt-1 h-2 w-2 rounded-full bg-amber-500"></span>
                  <span><strong class="text-slate-900">/src/client.tsx</strong> is inlined via &lt;script inline&gt;</span>
                </li>
                <li class="flex items-start gap-2">
                  <span class="mt-1 h-2 w-2 rounded-full bg-amber-500"></span>
                  <span>Tailwind utilities are generated by bun-plugin-tailwind</span>
                </li>
              </ul>

              <div class="mt-6 rounded-2xl border border-amber-200/70 bg-amber-50 p-4">
                <p class="text-[0.62rem] uppercase tracking-[0.32em] text-slate-500">Status</p>
                <div id="status" class="mt-2 text-sm font-semibold text-teal-700">Ready</div>
              </div>
            </section>

            <section class="animate-[fadeUp_0.8s_ease-out] rounded-3xl border border-amber-200/60 bg-white/80 p-7">
              <h2 class="text-xl font-semibold text-slate-900">API check</h2>
              <p class="mt-3 text-sm text-slate-600">
                Hit /api/hello and inspect the response.
              </p>
              <button
                id="fetch-button"
                class="mt-6 w-full rounded-2xl bg-teal-600 px-4 py-3 text-sm font-semibold text-white shadow-[0_16px_40px_-24px_rgba(13,148,136,0.6)] transition hover:-translate-y-0.5 hover:bg-teal-500 disabled:cursor-not-allowed disabled:opacity-60 disabled:shadow-none"
              >
                Fetch API
              </button>
              <pre id="output" class="mt-4 min-h-[120px] whitespace-pre-wrap rounded-2xl border border-amber-200/70 bg-amber-50 p-4 text-xs text-slate-800"></pre>
            </section>
          </main>
        </div>
      </div>
      <script inline src="/src/client.tsx"></script>
    </body>
  </html>
)

const app = new Hono()

app.get('/api/hello', (c) => {
  return c.json({ message: 'Hello from Hono on Bun!' })
})

app.get('/', (c) => c.html(<Page />))

export default app
